In [ ]:
# Data Visualization
# BTech Computer Science Stream , January 2025
# Week 3 NumPy Basics: Arrays and Vectorized Computation - Demonstration Code
# Name: Rajesh Gopakumar, Reg Number , Date: 06/01/2025

**Note**

1.   **Triple ###** in each cell is description(explanation, information) for the code.
2.   **Single #** need to be removed for sequential execution of the code.



# **NumPy**
 short for Numerical Python, is one of the most important foundational packages for numerical computing in Python.

**NumPy advantages**
1. *ndarray*, an efficient multidimensional array providing fast arrayoriented arithmetic operations and flexible broadcasting
capabilities.
2. Mathematical functions for fast operations on entire arrays of data
without having to write loops.
3. Tools for reading/writing array data to disk and working with
memory-mapped files.
4. Linear algebra, random number generation, and Fourier transform
capabilities.
5. A C API for connecting NumPy with libraries written in C, C++,
or FORTRAN. This provides a Dynamic and easyto-use interface.

**Why numPy is important**
* **NumPy** internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of
algorithms written in the C language can operate on this memory
without any type checking or other overhead. NumPy arrays also
use much less memory than built-in Python sequences.
* **NumPy** operations perform complex computations on entire arrays
without the need for Python for loops, which can be slow for
large sequences. NumPy is faster than regular Python code because
its C-based algorithms avoid overhead present with regular
interpreted Python code.
Naming Convention - Use descriptive names indicating the content of the array. Use 'arr' as suffix or prefix, Can also convey dimensions, shape, or type. Use underscores (snake_case) for better readability

In [ ]:
### performance difference between pure python and numpy execution
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [ ]:
### %timeit calculates the time for the below line in a cell.
### %%timeit calculates time for the entire cell.
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]
# my_list2 = [x * 2 for x in my_list]

1.07 ms ± 120 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
72.1 ms ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
### Some mathematical operations
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data * 10

In [ ]:
data + data

# ***ndarrays***
**The NumPy *ndarray*: A Multidimensional Array Object**

An ndarray is a generic multidimensional container for **homogeneous data**; that is, all of the elements must be the same type.
Every array has a **shape**, a tuple indicating the size of each dimension, and a **dtype**, an object describing the data type of the array.

In [ ]:
data.shape
# data.dtype

In [ ]:
### Creating ndarrays from a list
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
### multidimensional array (list of lists) from equal-length lists
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

In [ ]:
### ndim and shape attributes for a multidimentional array
arr2.ndim
#arr2.shape

In [ ]:
### dtype, n object describing the data type of the array
arr1.dtype
#arr2.dtype

In [ ]:
### other functions to create arrays
np.zeros(10)
#np.zeros((3, 6))
#np.empty((2, 3, 2)) # uninitialied array (garbage values)
#np.ones(10)
np.eye(3) # identity

***iNote ***:It’s not safe to assume that np.empty will return an array of all zeros. This function returns uninitialized memory and thus may contain non-zero “garbage” values.

In [ ]:
### "arange" is an array-valued version of the built-in Python range function
np.arange(15)
#arange(start(optional),stop,step(optional))
#np.arange(3,15,3)

NumPy is focused on numerical computing, the data type, if not specified will in many cases be float64 (floating point).

**Data Types for ndarrays**
The data type or ***dtype*** is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data.

In [2]:
### dtype
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
#arr2.dtype

dtype('float64')

In [ ]:
### You can explicitly convert or cast an array from one dtype to another using ndarray’s "astype" method
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
#float_arr = arr.astype(np.float64)
#float_arr
#float_arr.dtype

In [ ]:
### You can explicitly convert or cast an array from one dtype to another using ndarray’s "astype" method
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

In [ ]:
### you can use astype to convert strings to numeric form
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)
#numeric_strings = np.array(['1', '-9', '42'], dtype=np.string_)
#numeric_strings.astype(int)
#numeric_strings = np.array(["1", "-9", "42"], dtype=np.string_)
#numeric_strings.astype(np.int32)

In [ ]:
### another way of casting using dtype attribute
int_array = np.arange(10)
cal = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(cal.dtype)

***iNote*** :Calling ***astype*** always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

In [ ]:
### shorthand type code strings you can also use to refer to a dtype
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

# **Arithmetic with NumPy Arrays**

In [ ]:
### vectorization: batch operations on data without writing any for loops
### Arithmetic operations between equal-size arrays applies the operation element-wise
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
#arr * arr
#arr - arr

In [ ]:
### More operations Arithmetic operations with scalars propagate the scalar
### argument to each element in the array
1 / arr
#arr ** 2

In [ ]:
### Comparisons between arrays of the same size yield boolean arrays
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

# **Basic Indexing and Slicing**

In [ ]:
arr = np.arange(10)
arr
#arr[5]
#arr[5:8]
#arr[5:8] = 12 # if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection.
#arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***iNote*** : An important first distinction from Python’s built-in lists is that
array slices are views on the original array. This means that the data is not
copied, and any modifications to the view will be reflected in the source
array.

In [ ]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [ ]:
arr_slice[1] = 12345 # the mutations are reflected in the original array arr
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [ ]:
### The “bare” slice [:] will assign to all values in an array
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
### higher dimensional arrays; the elements at each index are no longer scalars but rather one-dimensional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

In [ ]:
### 2D Array
arr2d[0][2]
#arr2d[0, 2] #comma-separated list of indices to select individual elements

3

In [ ]:
### 3D Array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
### arr3d[0] is a 2 × 3 array
### The index 0 gives the First 2D array
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
### Both scalar values and arrays can be assigned to arr3d[0]
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

In [ ]:
### arr3d[1, 0] gives you all of the values whose indices start with (1, 0), forming a 1-dimensional array.
arr3d[1, 0]

In [ ]:
### Equivalant for arr3d[1,0] in two steps
x = arr3d[1]
x
x[0]

***iNote*** : Note that in all of these cases where subsections of the array have been selected, the returned arrays are views.

**Indexing with slices**

In [ ]:
### ndarrays can be sliced with the familiar syntax
arr
arr[1:6]

In [ ]:
### 2D array arr2d
arr2d

In [ ]:
### Slicing two-dimensional array arr2d
arr2d
arr2d[:2] # the first two rows of arr2d

In [ ]:
### multiple slices
arr2d[:2, 1:] #

***iNote*** : When slicing like this, you always obtain array views of the same number of dimensions.

In [ ]:
#$$ mixing integer indexes and slices, you get lower dimensional slices
arr2d

In [ ]:
### second row but only the first two columns
lower_dim_slice = arr2d[2, :2]
lower_dim_slice

In [ ]:
### shape of lower_dim_slice
lower_dim_slice.shape

In [ ]:
### third column but only the first two rows
arr2d[:2, 2]

In [ ]:
### a colon by itself means to take the entire axis, so you can slice only higher dimensional axes by doing
arr2d[:, :1]

In [ ]:
### assigning to a slice expression assigns to the whole selection [fig. 4.2]
arr2d[:2, 1:] = 0
arr2d

**Boolean Indexing**

In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
#names
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Suppose each name corresponds to a row in the data array and we wanted to select all the rows with corresponding name 'Bob'. Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. Thus, comparing names with the string 'Bob' yields a boolean array

In [ ]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

This boolean array can be passed when indexing the array

In [ ]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

The boolean array must be of the same length as the array axis it’s indexing. You can even mix and match boolean arrays with slices or integers

In [ ]:
data[names == "Bob", 1:]
data[names == "Bob", 1]

array([7, 0])

In [ ]:
### To select everything but 'Bob', you can either use != or negate the condition using ~:
names != "Bob"
#~(names == "Bob")
#data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
### The ~ operator can be useful when you want to invert a boolean array referenced by a variable
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

**Boolean arithmetic operators like & (and) and | (or)**

In [ ]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

array([[4, 7],
       [0, 6],
       [0, 0],
       [1, 2]])

***iNote*** : Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged

In [ ]:
### set all of the negative values in data to 0
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [ ]:
### Setting whole rows or columns using a one-dimensional boolean array
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

**Fancy Indexing**

indexing using integer arrays

In [ ]:
### creating an 8 x 4 array
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
### To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
### Using negative indices selects rows from the end
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
### Creating a multi dimentional array
arr = np.arange(32).reshape((8, 4))
arr
#arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were
selected. Regardless of how many dimensions the array has (here, only 2), the result of fancy indexing with multiple integer arrays is always onedimensional.

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

***iNote*** : Fancy indexing, unlike slicing, always copies the data
into a new array.

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

# **Transposing Arrays and Swapping Axes**

Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything

In [ ]:
### Creating a 3 x 5 array
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
### Arrays have the transpose method and also the special T attribute
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
### Inner matrix product
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr
#np.dot(arr.T, arr)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [ ]:
### Inner matrix product
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
#np.dot(arr.T, arr)

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
### The @ infix operator is another way to do matrix multiplication
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

**Swap axes**

In [ ]:
arr
arr.swapaxes(0, 1)

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

***iNote*** : swapaxes returns a view on the data without making a copy.

# **Universal Functions: Fast Element-Wise Array Functions**

A universal function, or ***ufunc***, is a function that performs element-wise
operations on data in ndarrays. You can think of them as fast vectorized
wrappers for simple functions that take one or more scalar values and
produce one or more scalar results.

In [ ]:
### unary ufuncs
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
### binary ufuncs take two arrays and return a single array as the result
x = np.random.standard_normal(8) # Draw samples from a standard Normal distribution (mean=0, stdev=1)
y = np.random.standard_normal(8)
x
y
#np.maximum(x, y) ### computed the element-wise maximum of the elements in x and y

array([ 1.32098715,  0.77784584,  0.25036766,  0.85827789, -1.12113236,
        1.17969142, -1.07593303,  1.38893343])

In [ ]:
### modf function: it returns the fractional and integral parts of a floating-point array
arr = np.random.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

array([ 1.,  0.,  1.,  0.,  2., -5., -9.])

In [ ]:
### add function
arr
#out = np.zeros_like(arr)
np.add(arr, 1)
#np.add(arr, 1, out=out)
#out

array([ 2.50260435,  1.26528323,  2.28635762,  1.17871431,  3.73618343,
       -4.6148079 , -8.87623834])

***iNote*** : Ufuncs accept an optional out argument that allows them to assign their results into an existing array rather than creating a new one.
Refer to table 4.3 and 4.4 for a listing of some of NumPy’s ufuncs.

# **Expressing Conditional Logic as Array Operations**
The ***numpy.where*** function is a vectorized version of the ternary
expression x if condition else y.

In [ ]:
###
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
###
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
###
result = np.where(cond, xarr, yarr)
result

In [ ]:
###
arr = np.random.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

In [ ]:
###
np.where(arr > 0, 2, arr) # set only positive values to 2

# **Mathematical and Statistical Methods**
A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as methods of the array class.

In [ ]:
### normally distributed random data and compute some aggregate statistics
arr = np.random.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
### Functions mean and sum take an optional axis argument that computes the statistic over the given axis, resulting in an array with one less dimension
xArr = np.array([[1, 2, 3], [4, 5, 6]])
xArr.mean(axis=1)
xArr.sum(axis=0)

In [ ]:
### cumsum and cumprod do not aggregate, instead produce an array of the intermediate results
xArr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
xArr.cumsum()
xArr.cumprod()

In [ ]:
### computed along the indicated axis according to each lower dimensional slice
xArr = np.array([[1, 2, 3], [4, 5, 6]])
xArr.cumsum(0)
#xArr.cumprod(1)

In [ ]:
###
xArr3d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
xArr3d
xArr3d.cumsum(axis=0)
xArr3d.cumprod(axis=1)

# **Methods for Boolean Arrays**


In [83]:
### Boolean values are coerced to 1 (True) and 0 (False). So "sum" is often used as a means of counting True values in a boolean array
#arr = np.random.standard_normal(100)
xArr = np.array([-5, 1, 2, -1, -4, -7, 3])
xArr
(xArr > 0).sum() # Number of positive values
(xArr <= 0).sum() # Number of non-positive values

4

In [76]:
### methods, "any" and "all" are useful especially for boolean arrays.
### "any" method tests whether one or more values in an array is True,
### "all" method checks if every value is True
bools = np.array([False, False, True, False])
bools.any()
#bools.all()

True

***iNote*** : These methods also work with non-boolean arrays, where non-zero
elements are treated as True.

# **Sorting**

In [63]:
### NumPy arrays can be sorted in-place with the sort method
arr = np.random.standard_normal(6)
arr
arr.sort()
arr

array([-0.85779058, -0.0928956 ,  0.12297438,  1.29199914,  1.61937963,
        2.48882931])

In [64]:
### Creating a multidimentional array
arr = np.random.standard_normal((5, 3))
arr

array([[ 0.43522325, -0.43933108,  2.24474216],
       [ 1.74481257, -0.11029615,  1.49901156],
       [ 1.54045699, -0.29167033, -1.276872  ],
       [-0.31921275, -0.42388507,  0.32128426],
       [-0.43196419, -0.66223105,  0.49909259]])

In [69]:
### sort each one-dimensional section of values in a multidimensional array in-place along an axis by passing the axis number to sort
xArr = np.array([[5, 1, 2], [4, 7, 3]])
xArr.sort(axis=0)
xArr
#xArr.sort(axis=1)
#xArr

array([[1, 2, 5],
       [3, 4, 7]])

In [72]:
### method np.sort returns a sorted copy of an array instead of modifying the array in-place
arr2 = np.array([5, -10, 7, 1, 0, -3])
np.sort(arr2)
sorted_arr2 = np.sort(arr2)
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

# **Unique and Other Set Logic**
NumPy has some basic set operations for one-dimensional ndarrays.

In [59]:
### np.unique, which returns the sorted unique values in an array
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
names
np.unique(names)
#ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
#np.unique(ints)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [60]:
### Pure Python alternative for np.unique
sorted(set(names))

['Bob', 'Joe', 'Will']

In [61]:
### np.in1d, tests membership of the values in one array in another, returning a boolean array
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

# **File Input and Output with Arrays**
NumPy is able to save and load data to and from disk in some text or binary
formats.

***np.save*** and ***np.load*** are the two functions for efficiently
saving and loading array data on disk in NumPy’s built-in binary format.

Arrays are saved by default in an uncompressed raw binary format with file extension .npy

In [52]:
### the file some_array.npy wil be created in the same directory where your Python script is running
arr = np.arange(10)
np.save("some_array", arr) ### give full path if you want to chage the destination "/path/to/directory/some_array.npy"

In [53]:
### The array on disk can then be loaded with np.load function
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
### save multiple arrays in an uncompressed archive using np.savez and passing the arrays as keyword arguments
np.savez("array_archive.npz", a=arr, b=arr)

In [55]:
arch = np.load("array_archive.npz")
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
### compressed array storing
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

In [ ]:
### rm shell command to remove file and directories
# !rm some_array.npy
# !rm array_archive.npz
# !rm arrays_compressed.npz

# **Linear Algebra**
**The function dot** for matrix multiplication


In [26]:
### dot, both an array method and a function in the numpy namespace
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [27]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [38]:
### A matrix product between a two-dimensional array and a suitably sized one-dimensional array results in a one-dimensional array
np.dot(x, np.ones(3))
#x @ np.ones(3) ###The @ symbol (as of Python 3.5) also works as an infix operator that performs matrix multiplication

array([ 6., 15.])

In [51]:
### numpy.linalg has a standard inverse and determinant implemented via linear algebra libraries BLAS, LAPACK
### see commonly used numpy.linalg functions online
from numpy.linalg import inv, det
X = np.random.standard_normal((5, 5))
#print(X)
mat = X.T @ X
#mat
#inv(mat)
#mat @ inv(mat)
#det(mat)