## WEEK 3 DEMO
### Chirag Rao K V

PC 66

reg 240962180

In [158]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(100))
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [81]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

4.39 ms ± 356 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
77.1 ms ± 9.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [82]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [83]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [84]:
### Creating ndarrays from a list
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [85]:
### Creating ndarrays from a list
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [86]:
arr1.dtype


dtype('float64')

In [87]:
### other functions to create arrays
np.zeros(10)

np.eye(3) # identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
### "arange" is an array-valued version of the built-in Python range function

np.arange(15)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [89]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype,arr2.dtype

(dtype('float64'), dtype('int32'))

In [90]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [91]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [92]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.str_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [93]:
### another way of casting using dtype attribute
int_array = np.arange(10)
cal = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(cal.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [94]:
### shorthand type code strings you can also use to refer to a dtype
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [95]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr,arr * arr,arr - arr

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 1.,  4.,  9.],
        [16., 25., 36.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [96]:
1 / arr,arr ** 2

(array([[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]]),
 array([[ 1.,  4.,  9.],
        [16., 25., 36.]]))

In [97]:
arr = np.arange(10)
arr,arr[5] # if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection.


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), np.int64(5))

In [98]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [99]:
arr_slice[1] = 12345 # the mutations are reflected in the original array arr
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [100]:
### The “bare” slice [:] will assign to all values in an array
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [101]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [102]:
arr2d[0][2]

np.int64(3)

In [103]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [106]:
arr3d[1, 0]

array([7, 8, 9])

In [107]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

In [108]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [109]:
lower_dim_slice = arr2d[2, :2]
lower_dim_slice

array([7, 8])

In [110]:
lower_dim_slice.shape

(2,)

In [111]:
arr2d[:2, 2]

array([3, 6])

In [112]:
#boolean indexing
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
#names
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [113]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [114]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [115]:
data[names == "Bob", 1:]
data[names == "Bob", 1]

array([7, 0])

In [116]:
names != "Bob"


array([False,  True,  True, False,  True,  True,  True])

In [117]:
### The ~ operator can be useful when you want to invert a boolean array referenced by a variable
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [118]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [119]:
### set all of the negative values in data to 0
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [120]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [121]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [122]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [123]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [124]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [125]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [126]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [127]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [128]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [129]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr
#np.dot(arr.T, arr)

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
#np.dot(arr.T, arr)

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [131]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [132]:
arr
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [133]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [134]:
x = np.random.standard_normal(8) # Draw samples from a standard Normal distribution (mean=0, stdev=1)
y = np.random.standard_normal(8)
x
y

array([-0.05383003,  0.84628368,  1.1101039 , -0.80324402, -0.58961822,
       -1.72092072, -0.11363207,  2.14562786])

In [135]:
arr = np.random.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

array([ 5.,  6.,  0.,  1., -3., -3.,  5.])

In [136]:
arr
#out = np.zeros_like(arr)
np.add(arr, 1)
#np.add(arr, 1, out=out)
#out

array([ 6.50486646,  7.12314428,  1.86609964,  2.06036105, -2.53108845,
       -2.22657596,  6.34041166])

In [137]:
###
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [138]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [139]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [140]:
arr = np.random.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[ 2, -2, -2, -2],
       [ 2,  2,  2,  2],
       [ 2, -2, -2,  2],
       [-2, -2, -2,  2]])

In [141]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.        , -1.20388877, -0.06847614, -0.14667217],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -1.47530928, -1.68738097,  2.        ],
       [-0.53970653, -0.34450617, -0.64703831,  2.        ]])

In [142]:
arr = np.random.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

np.float64(2.828281972070558)

In [143]:
xArr = np.array([[1, 2, 3], [4, 5, 6]])
xArr.mean(axis=1)
xArr.sum(axis=0)

array([5, 7, 9])

In [144]:
xArr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
xArr.cumsum()
xArr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0])

In [145]:
xArr = np.array([[1, 2, 3], [4, 5, 6]])
xArr.cumsum(0)

array([[1, 2, 3],
       [5, 7, 9]])

In [146]:
xArr3d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
xArr3d
xArr3d.cumsum(axis=0)
xArr3d.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [147]:
arr = np.random.standard_normal(6)
arr
arr.sort()
arr

array([-1.7783864 ,  0.5366502 ,  0.77205603,  1.24971814,  1.30257069,
        2.85849282])

In [148]:
arr = np.random.standard_normal((5, 3))
arr

array([[ 0.34806216,  1.84938473,  0.53982599],
       [-0.19941898, -0.20872397,  0.46391794],
       [-1.64587873,  0.59859715, -1.36501815],
       [ 0.0659857 , -0.6352622 , -0.17199708],
       [ 0.06213586,  1.1168101 ,  0.57554469]])

In [149]:
xArr = np.array([[5, 1, 2], [4, 7, 3]])
xArr.sort(axis=0)
xArr

array([[4, 1, 2],
       [5, 7, 3]])

In [150]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
np.sort(arr2)
sorted_arr2 = np.sort(arr2)
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

In [151]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
names
np.unique(names)
#ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
#np.unique(ints)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [152]:
sorted(set(names))

[np.str_('Bob'), np.str_('Joe'), np.str_('Will')]

In [153]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

C:\Users\chira\AppData\Local\Temp\ipykernel_26800\1293837718.py:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2, 3, 6])


array([ True, False, False,  True,  True, False,  True])

In [154]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x,y,x.dot(y)

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 6., 23.],
        [-1.,  7.],
        [ 8.,  9.]]),
 array([[ 28.,  64.],
        [ 67., 181.]]))

In [155]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [156]:
np.dot(x, np.ones(3))


array([ 6., 15.])

In [157]:
from numpy.linalg import inv, det
X = np.random.standard_normal((5, 5))
#print(X)
mat = X.T @ X
mat

array([[ 2.85827572,  0.77677136,  1.57256281, -2.10153617, -2.51578178],
       [ 0.77677136,  4.09087218, -4.81191741, -3.45669981, -0.43066056],
       [ 1.57256281, -4.81191741, 11.05612909,  1.2068585 ,  0.44310479],
       [-2.10153617, -3.45669981,  1.2068585 ,  4.83675145,  0.33793536],
       [-2.51578178, -0.43066056,  0.44310479,  0.33793536,  6.22886249]])