## 1. Generate a 3x4 NumPy array with random integers between 1 and 50.   

a. Calculate and print the Mean, Median, and Standard Deviation of the array 

b. Print the Sum of all elements and the sum of each row. 

c. Reshape the 3x4 array into a 2x6 array and print it. 

### Chirag Rao K V

PC 66

reg 240962180

In [1]:
import numpy as np


In [2]:
array = np.random.randint(1,50,size = (3,4))
array

array([[34, 22, 23, 20],
       [ 2, 24, 11, 40],
       [22, 27, 40, 44]], dtype=int32)

In [3]:
mean = np.mean(array)
medain = np.median(array)
standard_deviation = np.std(array)

In [4]:
print(f"mean = {mean}, medain = {medain}, standard deviation = {standard_deviation}")

mean = 25.75, medain = 23.5, standard deviation = 11.769487386175038


In [5]:
# sum of all the elements
np.sum(array)

np.int64(309)

In [6]:
# sum of elements of row
np.sum(array, axis =1)

array([ 99,  77, 133])

In [7]:

array.resize(2,6,refcheck=False)
array

array([[34, 22, 23, 20,  2, 24],
       [11, 40, 22, 27, 40, 44]], dtype=int32)

## 2. Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations 

a. Matrix addition 

b. Matrix subtraction 

c. Matrix multiplication (element-wise and dot product) 

d. Transpose of a matrix 

e. Determinant and inverse (if applicable) 

In [8]:
array1 = np.random.randint(1,50,size = (3,3))
array2 = np.random.randint(1,50,size = (3,3))
array1,array2

(array([[14, 21, 12],
        [18,  4, 21],
        [42, 48, 32]], dtype=int32),
 array([[19, 19,  3],
        [ 8, 37, 22],
        [41, 10,  8]], dtype=int32))

In [9]:
#addition of martix
np.add(array1,array2)

array([[33, 40, 15],
       [26, 41, 43],
       [83, 58, 40]], dtype=int32)

In [10]:
#Multiplication (dot product)
np.dot(array1,array2)

array([[ 926, 1163,  600],
       [1235,  700,  310],
       [2494, 2894, 1438]], dtype=int32)

In [11]:
#Multiplication (dot product)
np.multiply(array1,array2)

array([[ 266,  399,   36],
       [ 144,  148,  462],
       [1722,  480,  256]], dtype=int32)

In [12]:
print(f"ARRAY =\n{array1}\nAfte transpose =\n{np.transpose(array1)}")

ARRAY =
[[14 21 12]
 [18  4 21]
 [42 48 32]]
Afte transpose =
[[14 18 42]
 [21  4 48]
 [12 21 32]]


In [13]:
print(f"The determinant = {np.linalg.det(array1)}")

The determinant = 2458.0000000000014
