## 1. Generate a 3x4 NumPy array with random integers between 1 and 50.   

a. Calculate and print the Mean, Median, and Standard Deviation of the array 

b. Print the Sum of all elements and the sum of each row. 

c. Reshape the 3x4 array into a 2x6 array and print it. 

In [44]:
import numpy as np


In [70]:
array = np.random.randint(1,50,size = (3,4))
array

array([[27,  7, 30, 10],
       [41,  1, 34, 28],
       [27, 47, 46,  6]])

In [71]:
mean = np.mean(array)
medain = np.median(array)
standard_deviation = np.std(array)

In [72]:
print(f"mean = {mean}, medain = {medain}, standard deviation = {standard_deviation}")

mean = 25.333333333333332, medain = 27.5, standard deviation = 15.2443067697055


In [73]:
# sum of all the elements
np.sum(array)

304

In [74]:
# sum of elements of row
np.sum(array, axis =1)

array([ 74, 104, 126])

In [75]:

array.resize(2,6,refcheck=False)
array

array([[27,  7, 30, 10, 41,  1],
       [34, 28, 27, 47, 46,  6]])

## 2. Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations 

a. Matrix addition 

b. Matrix subtraction 

c. Matrix multiplication (element-wise and dot product) 

d. Transpose of a matrix 

e. Determinant and inverse (if applicable) 

In [76]:
array1 = np.random.randint(1,50,size = (3,3))
array2 = np.random.randint(1,50,size = (3,3))
array1,array2

(array([[32, 29, 25],
        [36,  8, 14],
        [26, 11, 20]]),
 array([[41, 29,  3],
        [ 6,  2, 45],
        [21, 14, 13]]))

In [77]:
#addition of martix
np.add(array1,array2)

array([[73, 58, 28],
       [42, 10, 59],
       [47, 25, 33]])

In [78]:
#Multiplication (dot product)
np.dot(array1,array2)

array([[2011, 1336, 1726],
       [1818, 1256,  650],
       [1552, 1056,  833]])

In [79]:
#Multiplication (dot product)
np.multiply(array1,array2)

array([[1312,  841,   75],
       [ 216,   16,  630],
       [ 546,  154,  260]])

In [80]:
print(f"ARRAY =\n{array1}\nAfte transpose =\n{np.transpose(array1)}")

ARRAY =
[[32 29 25]
 [36  8 14]
 [26 11 20]]
Afte transpose =
[[32 36 26]
 [29  8 11]
 [25 14 20]]


In [81]:
print(f"The determinant = {np.linalg.det(array1)}")

The determinant = -5431.999999999993
