In [42]:
def identify_magic_square(array):
    if array.shape[0] != array.shape[1]:
        print("not a square matrix!!!")
    else:
        sum_row = 0
        sum_col = 0
        sum_diag1 = 0
        sum_diag2 = 0
       
        for i in range(array.shape[0]):
            sum_row =sum(array[i,:])
            sum_col = sum(array[])
        if(sum_all_rows[1] == sum_all_col[1] & sum_all_col[1] == sum_diag1 & sum_diag1 == sum_diag2):
            print(f"Array \n{array}\nIs a square matrix ")
        else:
            print(f"Array \n{array}\nIs not a square matrix ")

In [43]:
import numpy as np

In [48]:
array = np.array([[8,1,0],[3,5,7],[4,9,2]])

In [49]:
identify_magic_square(array)

Array 
[[8 1 0]
 [3 5 7]
 [4 9 2]]
Is a square matrix 


Write a Python code block that inputs a sentence from the user. 

Count the frequency of each word in the sentence and store the 

result in a dictionary. Prints the dictionary with words as keys 

and their frequencies as values. 

In [57]:
inp_str = str(input())

haha \\n haha


'haha \\\\n haha'