# LAB 1
Chirag Rao K V

240962180

roll no: 16

In [60]:
import numpy as np

Convert 1D array to 2D array

In [ ]:
oned = np.array([2,3,4,1,2,3])
twod = oned.reshape(2,3)
# using reshape to get 2d array
print(f"after reshape (2,3):\n {twod}")
print(f"after reshape (3,2):\n {oned.reshape(3,2)}")


after reshape (2,3):
 [[2 3 4]
 [1 2 3]]
after reshape (3,2):
 [[2 3]
 [4 1]
 [2 3]]


Replace all odd numbers in the array

In [ ]:
def replace_odd(replace, array):
    # function to replace odd nmbers with a constant
    for i in range(0,len(array)):
        if array[i] % 2 != 0:
            array[i] = replace
    return array

replace_odd(1,oned)

array([2, 1, 4, 1, 2, 1])

Find the position of:

elements in x where its value is more than its corresponding element in y and elements in x where its value is equal to its corresponding in y

In [ ]:
def compare_array(x,y):
    # finds the index where x = y and x< y
    n = min(len(x),len(y))
    same = []
    more = []
    for i in range(0,n):
        if x[i] < y[i]:
            same.append(i)
        if x[i] == y[i]:
            more.append(i)
    return same,more
compare_array(oned,np.array([2,3,0,1,6,1])) 

([1, 4], [0, 3, 5])

Extract the first four columns of the 2d array

In [64]:
assign_4 = np.arange(100).reshape(5,-1)
assign_4[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

## Additional Questions

Generate a 1D array of 10 random integers, each integer whould be a number between 30 and 40 (inclusive)

In [65]:
rng = np.random.default_rng()
rng.integers(30,40,10)

array([30, 36, 30, 37, 39, 34, 30, 31, 39, 31])

Consider the following matrices:

A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))
Write a python program to perform the following using Numeric Python (numpy).

i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.

ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C

iii) Product of two matrices A and B, and print the resultant matrix D

iv) Sort the elements of resultant matrix C and print the resultant Matrix E.

v) Transpose the Matrix E and print the result

In [66]:
def process_mat(a,b):
    if a.shape != b.shape:
        return 
    n,m = a.shape
    c = np.zeros((n,m))
    e = np.zeros((n,m))
    suma = 0
    for i in range(0,n):
        for j in range(0,m):
            c[i][j] = a[i][j] + b[i][j]
            e[i][j] = a[i][j] - b[i][j]
    suma = a.sum()
    sumc = b.sum(0)
    sumr = c.sum(1)
    d = a * b
    csort = np.sort(c.reshape(-1)).reshape(n,m)
    print(f"a - b = E: \n{e}")
    print(f"E.T\n{e.T}")
    print(f"sum of elements f a {suma}")
    print(f"sum of col of b \n{sumc}")
    print(f"sum of row of c \n{sumr}")
    print(f"a * b = \n{d}")
    print(f"a + b = \n{c}")

a = np.array([[1,2,3],[4,5,6],[7,8,10]])
b = np.array([[7,8,10],[4,5,6],[1,2,3]])
process_mat(a,b)

a - b = E: 
[[-6. -6. -7.]
 [ 0.  0.  0.]
 [ 6.  6.  7.]]
E.T
[[-6.  0.  6.]
 [-6.  0.  6.]
 [-7.  0.  7.]]
sum of elements f a 46
sum of col of b 
[12 15 19]
sum of row of c 
[31. 30. 31.]
a * b = 
[[ 7 16 30]
 [16 25 36]
 [ 7 16 30]]
a + b = 
[[ 8. 10. 13.]
 [ 8. 10. 12.]
 [ 8. 10. 13.]]
