# NumPY

In [2]:
import numpy as np

In [3]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_list = list(range(10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Time Required
NUMPY vs NO NUMPY

In [5]:
%timeit array_2 = array*2

984 ns ± 105 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
%timeit list_2 = my_list*2

125 ns ± 42 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


## Initializing an array using numpy


In [7]:
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])   
data = data*10
print(type(data[0][0])) # datatype of array is float 
data

<class 'numpy.float64'>


array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [8]:
data+data

array([[ 30.,  -2.,  60.],
       [  0., -60., 130.]])

In [9]:
data1 = [6,5,4.4,0]
array1 = np.array(data1)
print(type(array1[0]))
array1

<class 'numpy.float64'>


array([6. , 5. , 4.4, 0. ])

In [10]:
array = np.arange(2,10,2)
array

array([2, 4, 6, 8])

In [11]:
array3 = np.array([1,2,3],dtype=int)
array3.dtype

dtype('int64')

In [12]:
array3 = np.array([1,2,2,3],dtype=float)
array3.dtype

dtype('float64')

In [13]:
string1 = np.array("12","34","23",dtype=np.bytes_)
string1.astype(int)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

### Slicing in array

In [18]:
array3[0:3] = 1
array3

array([1., 1., 1., 3.])

In [35]:
array3d = np.array([[[1,2,3],[1,2,3]],[[5,6,7],[3,4,5]]])


In [37]:
old = array3d[0]
array3d[0] = 42
print("\n")
array3d[0] = old
print(array3d)



[[[42 42 42]
  [42 42 42]]

 [[ 5  6  7]
  [ 3  4  5]]]


In [44]:
names = np.array(["asd","asdf"])
data = np.array([[[1,2],[12,34]],[[22,33],[23,34]]])
print(names)
print(data)

['asd' 'asdf']
[[[ 1  2]
  [12 34]]

 [[22 33]
  [23 34]]]


In [46]:
mask = (names = "asd")|(names="asdf")

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3908713988.py, line 1)